name: Go Test Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Go tests with Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.1'

      - name: Cleanup Before
        if: always()
        run: docker system prune -a --volumes --force

      - name: Build and Install
        run: make install

      - name: Test
        run: make test

      - name: Cleanup After
        if: always()
        run: docker system prune -a --volumes --force